# Cross-compiles libgpiod (C library + C++ bindings) from source via
# meson, and defines icom::libgpiod_c / icom::libgpiod_cxx imported
# targets for it. See docs/CROSS_COMPILE.md "Building libgpiod from
# source" for the full rationale; the short version: no distro ships a
# prebuilt libgpiod for genuine ARMv6, so the only way to get it without
# a full Raspberry Pi OS sysroot is to build it ourselves, with the same
# compiler this project itself is being built with.
#
# meson, not autotools: as of the version this pins (v2.3.1), upstream
# libgpiod's build is meson-only -- there is no configure.ac/Makefile.am
# to fall back to.
#
# Static libraries: so a `scripts/deploy.sh`-style "just copy the binary
# over" deployment keeps working, with no libgpiod*.so to also install
# and keep version-matched on the target.
include(ExternalProject)

function(icom_build_libgpiod_from_source)
    find_program(ICOM_MESON_EXECUTABLE meson)
    find_program(ICOM_NINJA_EXECUTABLE ninja)

    set(_icom_missing_tools "")
    if(NOT ICOM_MESON_EXECUTABLE)
        list(APPEND _icom_missing_tools "meson")
    endif()
    if(NOT ICOM_NINJA_EXECUTABLE)
        list(APPEND _icom_missing_tools "ninja")
    endif()

    if(_icom_missing_tools)
        list(JOIN _icom_missing_tools "', '" _icom_missing_tools_joined)
        message(FATAL_ERROR
            "ICOM_LIBGPIOD_BUILD_FROM_SOURCE=ON needs '${_icom_missing_tools_joined}' "
            "on the HOST (not found on PATH) -- it/they orchestrate the "
            "cross-build; they do not themselves run on the target. Install "
            "with e.g. 'apt install meson ninja-build', or set "
            "-DICOM_LIBGPIOD_BUILD_FROM_SOURCE=OFF and provide libgpiod via "
            "ICOM_PI_SYSROOT instead.")
    endif()

    if(NOT CMAKE_CROSSCOMPILING)
        message(FATAL_ERROR
            "ICOM_LIBGPIOD_BUILD_FROM_SOURCE is for cross-compiling only -- "
            "on the host-dev preset, libgpiod isn't used at all (see "
            "ICOM_WITH_LIBGPIOD in the top-level CMakeLists.txt).")
    endif()

    set(ICOM_LIBGPIOD_GIT_URL "https://github.com/brgl/libgpiod.git" CACHE STRING
        "Repository to fetch libgpiod from when building it from source (a mirror of the canonical kernel.org repo)")
    set(ICOM_LIBGPIOD_GIT_TAG "v2.3.1" CACHE STRING
        "libgpiod tag/commit to build when building it from source")
    mark_as_advanced(ICOM_LIBGPIOD_GIT_URL ICOM_LIBGPIOD_GIT_TAG)

    set(_icom_libgpiod_root "${CMAKE_BINARY_DIR}/third_party/libgpiod")
    set(_icom_libgpiod_install_dir "${_icom_libgpiod_root}/install")
    set(_icom_libgpiod_cross_file "${_icom_libgpiod_root}/meson-cross-file.ini")

    # meson has its own cross-file format -- entirely separate from
    # CMake's toolchain file -- so the compiler/flags this project itself
    # uses (ICOM_TARGET_CPU_FLAGS, set by
    # cmake/toolchain-arm-linux-gnueabihf.cmake) have to be re-expressed
    # here rather than simply inherited.
    separate_arguments(_icom_flags_list UNIX_COMMAND "${ICOM_TARGET_CPU_FLAGS}")
    set(_icom_flags_quoted "")
    foreach(_icom_flag ${_icom_flags_list})
        string(APPEND _icom_flags_quoted "'${_icom_flag}', ")
    endforeach()

    file(MAKE_DIRECTORY "${_icom_libgpiod_root}")
    file(WRITE "${_icom_libgpiod_cross_file}" "\
# Generated by src/gpio/cmake/BuildLibgpiodFromSource.cmake -- do not edit,
# it is regenerated on every CMake configure.
[binaries]
c = '${CMAKE_C_COMPILER}'
cpp = '${CMAKE_CXX_COMPILER}'
ar = '${CMAKE_AR}'
strip = '${CMAKE_STRIP}'
pkg-config = 'pkg-config'

[built-in options]
c_args = [${_icom_flags_quoted}]
cpp_args = [${_icom_flags_quoted}]
c_link_args = [${_icom_flags_quoted}]
cpp_link_args = [${_icom_flags_quoted}]
default_library = 'static'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'arm1176jzf-s'
endian = 'little'
")

    ExternalProject_Add(icom_libgpiod_ext
        GIT_REPOSITORY "${ICOM_LIBGPIOD_GIT_URL}"
        GIT_TAG "${ICOM_LIBGPIOD_GIT_TAG}"
        GIT_SHALLOW TRUE
        # Same as alsa-lib's recipe: skip the per-build git update (and the
        # reconfigure/rebuild/reinstall it triggers) for a pinned tag;
        # changing ICOM_LIBGPIOD_GIT_TAG still re-fetches.
        UPDATE_DISCONNECTED TRUE
        PREFIX "${_icom_libgpiod_root}"
        INSTALL_DIR "${_icom_libgpiod_install_dir}"
        CONFIGURE_COMMAND
            "${ICOM_MESON_EXECUTABLE}" setup <BINARY_DIR> <SOURCE_DIR>
            "--cross-file=${_icom_libgpiod_cross_file}"
            --prefix=<INSTALL_DIR>
            --libdir=lib
            --default-library=static
            -Dbindings-cxx=enabled
            -Dtools=disabled
            -Dtests=disabled
            -Dexamples=disabled
            -Dbindings-python=disabled
            -Dbindings-glib=disabled
            -Ddbus=disabled
            -Dsystemd=disabled
            -Dgpioset-interactive=disabled
        BUILD_COMMAND "${ICOM_NINJA_EXECUTABLE}" -C <BINARY_DIR>
        INSTALL_COMMAND "${ICOM_NINJA_EXECUTABLE}" -C <BINARY_DIR> install
        BUILD_BYPRODUCTS
            "${_icom_libgpiod_install_dir}/lib/libgpiod.a"
            "${_icom_libgpiod_install_dir}/lib/libgpiodcxx.a"
        LOG_CONFIGURE TRUE
        LOG_BUILD TRUE
        LOG_INSTALL TRUE
        USES_TERMINAL_CONFIGURE TRUE
        USES_TERMINAL_BUILD TRUE
        USES_TERMINAL_INSTALL TRUE
    )

    # CMake requires an IMPORTED target's INTERFACE_INCLUDE_DIRECTORIES to
    # already exist at generate time, even though the real headers won't
    # land there until this ExternalProject's install step actually runs
    # at build time -- an empty placeholder now satisfies that check.
    file(MAKE_DIRECTORY "${_icom_libgpiod_install_dir}/include")

    add_library(icom_libgpiod_c STATIC IMPORTED GLOBAL)
    set_target_properties(icom_libgpiod_c PROPERTIES
        IMPORTED_LOCATION "${_icom_libgpiod_install_dir}/lib/libgpiod.a"
        INTERFACE_INCLUDE_DIRECTORIES "${_icom_libgpiod_install_dir}/include"
    )
    add_dependencies(icom_libgpiod_c icom_libgpiod_ext)
    add_library(icom::libgpiod_c ALIAS icom_libgpiod_c)

    add_library(icom_libgpiod_cxx STATIC IMPORTED GLOBAL)
    set_target_properties(icom_libgpiod_cxx PROPERTIES
        IMPORTED_LOCATION "${_icom_libgpiod_install_dir}/lib/libgpiodcxx.a"
        INTERFACE_INCLUDE_DIRECTORIES "${_icom_libgpiod_install_dir}/include"
        INTERFACE_LINK_LIBRARIES icom_libgpiod_c
    )
    add_dependencies(icom_libgpiod_cxx icom_libgpiod_ext)
    add_library(icom::libgpiod_cxx ALIAS icom_libgpiod_cxx)
endfunction()
